### ISSUE TITLE
Current time vertical line

### ISSUE THREAD

**Issue by x1mrdonut1x** [antvis/G2#2864]
Is it possible to render a vertical line on an timeseries Area/Line chart that shows the current time?

**Comment by DarrenPei** [comment]
Please elaborate your scene. The current time is usually at the end of time series. You can try the grid attr of axis by the way.

**Comment by DarrenPei** [comment]
You can use chart.guide().line() and use javascript to identify the current time. But you need to adjust the X coordinate of start point and end point because of the normalization operation.
```js
import { Chart } from '@antv/g2';

const data = [

  { year: '2009', value: 70 },
  { year: '2010', value: 120 },
  { year: '2011', value: 140 },
  { year: '2012', value: 80 },
  { year: '2013', value: 250 },
  { year: '2014', value: 280 },
  { year: '2015', value: 400 },
  { year: '2016', value: 400 },
  { year: '2017', value: 800 },
  { year: '2018', value: 1000 }
];
const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
});

chart.data(data);
chart.scale({
  year: {
    range: [0, 1],
  },
  value: {
    min: 0,
    nice: true,
  },
});

chart.tooltip({
  showCrosshairs: true, // 展示 Tooltip 辅助线
  shared: true,
});

chart.line().position('year*value').label('value');
chart.point().position('year*value');

chart.guide().line({
    start: [ 5, 0 ], // the start point of the guide line
    end: [ 5, 1000 ], //the end point of the guide line
    text: {
      position: 'start',
      autoRotate: false,
      content: 'current time'
    }
});

chart.render();
```
Demo see:  https://codesandbox.io/s/practical-wiles-w3vxp?file=/src/index.js

API docs from https://g2-v3.antv.vision/zh/docs/manual/tutorial/guide

data from  https://g2.antv.vision/zh/examples/gallery/column#column3

Normalization operation  https://g2-v3.antv.vision/zh/docs/manual/advanced/data-flow

**Comment by Me-Momo** [comment]
you can try `chart.annotation().line({ .... })` in G2 4.x, API: https://g2.antv.vision/en/docs/manual/tutorial/annotation

**Comment by DarrenPei** [comment]
I used chart.annotation().line to draw the line and it's great.
```js
chart.annotation().line({
  start: ['2016',0],
  end: ['2016', 1000],
  text: {
    position: 'start',
    autoRotate: false,
    content: 'current time'
  }
})
```
see Demo
https://codesandbox.io/s/aged-sun-4eph2?file=/src/index.js
