### ISSUE TITLE
Can the start and end angles of the polar coordinates be set to counterclockwise in v4.x?

### ISSUE THREAD

**Issue by PomeloMan** [antvis/G2#3051]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The problem is same as [issue#945](https://github.com/antvis/G2/issues/945), but the v4 version cannot use the v3 method to solve this demand

### What does the proposed API look like?
chart.coordinate('polar', { innerRadius: 0.1 }).transpose().scale(1,-1); // Unable to achieve the expected effect
Is there any other way to achieve this requirement in v4.x?

**Comment by SentretC** [comment]
Can't help much but to demonstrate the problem.

### In v3
Open the official [radial bar chart](https://g2-v3.antv.vision/en/examples/bar/basic#radial-bar) example, which looks like this:
![](https://user-images.githubusercontent.com/44996835/100953932-87fa9680-354e-11eb-8188-6d6d2ded84e2.png)
The label '0.21' overflows, also I wonder why the percentage can be greater than 100%, but otherwise looks good.

Add `.scale(1, -1)` and It becomes:
![](https://user-images.githubusercontent.com/44996835/100954750-22a7a500-3550-11eb-841a-d12318fbbb95.png)
The chart flips upside-down, thus becomes counter-clockwise. The labels fall on the background instead of the bars.

Change to `.scale(-1, 1)`:
![](https://user-images.githubusercontent.com/44996835/100955311-47504c80-3551-11eb-8d92-cc48747df11d.png)
Now it's flipped horizontally, with the axis labels overlapping the bars.

Use `.reflect('y')` instead:
![](https://user-images.githubusercontent.com/44996835/100955683-e9703480-3551-11eb-8941-740f4f06f4e8.png)
Looks like the data is provided in reverse order. The chart is still clockwise.

But `.reflect('x')` goes wrong:
![](https://user-images.githubusercontent.com/44996835/100955939-73200200-3552-11eb-802b-1bf6ca053ace.png)
The end points of the bars are the same as the .scale(-1, 1) case, but the bars go in the wrong direction.

### In v4
Open the [corresponding example](https://g2.antv.vision/en/examples/bar/basic#radial-bar).
![](https://user-images.githubusercontent.com/44996835/100957417-56d19480-3555-11eb-91ca-51c857acf391.png)
The labels are not shown, and the topmost axis label is cut off a little bit when the chart is small.

Add `.scale(1, -1)`:
![](https://user-images.githubusercontent.com/44996835/100958252-f9d6de00-3556-11eb-8b62-15538b22ab20.png)
The end points of the bars are the same as in v3, but the bars go in the wrong direction, like using `.reflect('x')` in v3.

`.scale(-1, 1)`:
![](https://user-images.githubusercontent.com/44996835/100958774-eb3cf680-3557-11eb-8272-f2406b86f392.png)
Same as using `.reflect('x')` in v3 (except for the missing labels).
`.reflect('x')` looks the same as above.

`.reflect('y')`:
![](https://user-images.githubusercontent.com/44996835/100959186-b2e9e800-3558-11eb-91bd-71a75754843f.png)
Like in v3, with the axis labels go beneath the bars.

**Comment by SentretC** [comment]
I used `toDataURL()` to get those images. Seems that the transparency is lost during upload...

**Comment by hustcc** [comment]
We will not fix them in v4 due to problems in the program's architecture design, But we will process them in G2 v5.

**Comment by pearmini** [comment]
You can track the status of this issue：https://github.com/antvis/G2/issues/3646
