### ISSUE TITLE
tickCount config [Update: Candlestick doesn't work with exponential value or toFixed()]

### ISSUE THREAD

**Issue by karimhossenbux** [antvis/g2#363]
Could you elaborate how tickCount works and what the value means? I'm trying different value and some candlestick are just strait flat on the bottom 

Value are there, hover is working, and when changing tickCount value for the Price, I get some that didn't work to work again but not all.

Is this a bug? Is it possible to "calculate" the correct value to put in tickCount?

Thank you in advance!
  
![candlestick](https://i.imgur.com/2tS1DKL.png)

**Comment by leungwensen** [comment]
Can U provide a CodePen Link which can reproduce the issue?

**Comment by karimhossenbux** [comment]
I know why it's not working, it's because some values are in exponential.
I've tried to convert them with transform/map but I'm only able to convert 6.4e-7 to String "0.00000064", I can't find a way of making it a Number or Float (using BigNumber.js)

Do you it's possible de make g2 compatible with exponential? or convert the exponential value and use the String?

**Comment by leungwensen** [comment]
`x.toFixed()` then use `cat`?

**Comment by karimhossenbux** [comment]
- to.Fixed() return me a String value "0.00000064" and the graph is then empty.
- With exponential value, graph is bottom flat

Should the plugin be compatible with exp?

**Comment by leungwensen** [comment]
@karimhossenbux  If the problem is that there are two different kinds of number formats (`0.0064` or `6.4e-7`), then providing a way to unify values (e.g. in DataSet) might be better. If not, we'd better seek some way to support this case in G2's Ticks module.
`A CodePen Link` will be very helpful for me to get a bigger picture of this case, to help find out which one is the better solution.
